source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'AABlurAlertController' do

    target 'AABlurAlertControllerTests' do
        inherit! :search_paths

        pod 'Quick'
        pod 'Nimble'
        pod 'Nimble-Snapshots'
    end
end

